# src/config/exp001_gray-matter_mmse.yaml
# input: gray matter
# output: MMSE

# 1. 実験の基本情報
experiment_name: "MMSE_Prediction"
run_name: "Simple3DCNN_on_Gray-matter_to_MMSE"

# 2. データの指定
data:
  pickle_path: "data/processed/dataset_gray-matter.pkl"
  target_variable: "MMSE"
  tabular_input_features: []

# 3. モデルの指定
model:
  name: "Simple3DCNN"
  params: 
    dropout_rate: 0.3

# 4. 学習のパラメータ
training:
  optimizer:
    name: "Adam"
    params:
      learning_rate: 0.001

  loss: "mean_squared_error"
  batch_size: 8

  stages:
    - stage_name: "WarmupPhase"
      epochs: 50
      learning_rate: 0.001
      callbacks: []
    
    - stage_name: "FineTuningPhase"
      epochs: 50
      learning_rate: 0.001
      callbacks:
        - name: "EarlyStopping"
          params:
            monitor: "val_loss"
            patience: 15
            restore_best_weights: True
            verbose: 1
        - name: "ReduceLROnPlateau"
          params: 
            monitor: "val_loss"
            factor: 0.5
            patience: 5
            min_lr: 0.00001

# 5. 再現性のための設定
environment:
  seed: 42