# データパス設定
data: 
  processed_dir: 'data/derivatives/processed_data'
  csv_path: 'data/processed/structured_data.csv'
  output_dir: 'data/processed'

# データセット生成設定
dataset:
  path_templates:
    base: 'spm/norm/mw{subject}_T1w.nii'
    mask: 'spm/norm/wc1{subject}_T1w.nii' # マスクの設定 

  # マスク名（出力ファイル名に使用）
  mask_name: 'gray-matter'

  roi_processing_mode: 'crop_and_pad'

  target_columns:
    - 'MMSE'
    - 'CDR'
    - 'CDR_sum'
    - 'Moca-J'
    - 'gm_atrophy'
    - 'severity'
  
# モデル学習設定
training:
  test_size: 0.2
  random_state: 42

# 出力設定
output:
  filename_template: 'dataset_{mask_name}.pkl'

#'spm/norm/wc1{subject}_T1w.nii'
#'spm/norm/w{subject}_mask-hippocampus.nii'
#'spm/norm/w{subject}_mask-prefrontal-cortex.nii'
#'spm/norm/w{subject}_mask-parietal-lobe.nii'
#'spm/norm/w{subject}_mask-occipital-lobe.nii'
#'spm/norm/w{subject}_mask-temporal-lobe.nii'
#'spm/norm/w{subject}_mask-brain-stem.nii'